name: BE deploy uat branch
run-name: BE deploy uat branch

on:
  push:
    branches:
      - uat

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo 'build'
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: publish
        run: echo 'publishing'