name: BE deploy uat branch
run-name: BE deploy uat branch
on:
  push:
    branches:
      - 'uat'
    paths:
    - backend/**
jobs:
  build:
    runs-on: [self-hosted,backend-server-staging] # tag in server-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          ls
          echo "Buil image"

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: publish
        run: echo 'publishing'