name: FE-CI
run-name: FE-CI

on:
  pull_request:
    branches:
      - 'develop'
    paths:
        - frontend/**
defaults:
  run:
    working-directory: ./frontend
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Using docker to check convention code
        run: |
          echo "Start lint...."
          echo "Install tool..." #Install tool if github action is not built-in
          echo "Run demo."
          echo "Lint done."        